# Generated by Django 3.0.3 on 2020-02-13 21:45

# IMPORTS
# Python Core Imports

# Third Party Imports
from django.db import migrations

# Local Imports
import corefunctions


def initial_cities_data(apps, schemaEditor):
    """Will populate the "Cities" models will all the cities in the world."""
    Cities = apps.get_model('forecast', 'Cities')

    for city in corefunctions.all_cities:
        newCity = Cities.objects.create(name=city)
        newCity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_cities_data),
    ]
