# Generated by Django 3.0.3 on 2020-02-13 21:45

# IMPORTS
# Python Core Imports
import os
import json

# Third Party Imports
from django.db import migrations

# Local Imports


def initial_cities_data(apps, schemaEditor):
    """Will populate the "Cities" models will all the cities in the world."""
    Cities = apps.get_model('forecast', 'Cities')
    citiesDataPath = os.path.join(os.getcwd(), 'all_cities.json')
    with open(citiesDataPath) as jsonFile:
        citiesData = json.load(jsonFile)

    for city in citiesData:
        newCity = Cities.objects.create(name=city)
        newCity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_cities_data),
    ]
