# Generated by Django 3.0.3 on 2020-02-13 23:50

# IMPORTS
# Python Core Imports

# Third Party Imports
from django.db import migrations

# Local Imports
import corefunctions


def initial_forecasts_data(apps, schemeEditior):
    """Populates the "Forecast" model with dummy data for all cities"""
    Forecast = apps.get_model('forecast', 'Forecast')
    Cities = apps.get_model('forecast', 'Cities')

    for city in corefunctions.all_cities:
        newForecast = Forecast.objects.create(
            city=Cities.objects.get(name=city),
            humidity=-99,
            pressure=-99,
            temperature=-99,
            forecast_for=-99
        )
        newForecast.save()


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0003_auto_20200213_2327'),
    ]

    operations = [
        migrations.RunPython(initial_forecasts_data)
    ]
